version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: cleansoundstudio_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 20

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=UTC
      - LT_LOAD_ONLY=en,id,ja,es,fr,de
      # - API_KEY=your_strong_key    # opsional, jika mau proteksi
    volumes:
      - ./libretranslate_db:/db

  web:
    build:
      context: ..
      dockerfile: docker-file/Dockerfile
    container_name: cleansoundstudio_web
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,web,581ef486ef03.ngrok-free.app"
      DJANGO_CSRF_TRUSTED_ORIGINS: "https://581ef486ef03.ngrok-free.app,http://localhost:8000,http://127.0.0.1:8000"
      DJANGO_PORT: "8001"
    ports:
      - "8000:8001"
    volumes:
      - ..:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy
      libretranslate:
        condition: service_started

volumes:
  db_data:
  static_data:
  media_data: